### ISSUE TITLE
Upgrade Ace to v1.2.3

### ISSUE THREAD

**Issue by faloi** [codykrieger/ace-rails-ap#18]
Hi there!

Like a month ago, the Ace folks released [v1.2.3](https://github.com/ajaxorg/ace/releases/tag/v1.2.3). It's a minor release, but we need it because it adds some language modes we created to use in [Mumuki](http://mumuki.org), our educational project.

I'll try to do it myself and issue a pull request, please let me know if you have any directives.

**Comment by faloi** [comment]
Just for completeness, here is the changelog (our modes don't appear there, but they are included in the release):

```
2016.01.17 Version 1.2.3

* Bugfixes
  - fix memory leak in setSession (Tyler Stalder)
  - double click not working on linux/mac
  
* new language modes
  - reStructuredText (Robin Jarry)
  - NSIS (Jan T. Sott)
```

**Comment by codykrieger** [comment]
```
% rake release
ace-rails-ap 4.0.2 built to pkg/ace-rails-ap-4.0.2.gem.
Tagged v4.0.2.
Pushed git commits and tags.
Pushed ace-rails-ap 4.0.2 to rubygems.org.
```

**Comment by faloi** [comment]
Thanks @codykrieger! :smiley:

**Comment by codykrieger** [comment]
👌
