### ISSUE TITLE
Add charlesco's bash mode

### ISSUE THREAD

**Issue by Angel-Garcia-Fernandez** [codykrieger/ace-rails-ap#28]
As bash does not have its own mode, I would like to add charlesco's bash mode to ace-rails-ap.

https://github.com/charleso/ace-mode-bash

I have created a mode-bash.js with charlesco's rules in a fork.

https://github.com/Angel-Garcia-Fernandez/ace-rails-ap

**Comment by codykrieger** [comment]
Closed via #29.
