### ISSUE TITLE
404 errors in production

### ISSUE THREAD

**Issue by jmacdonald** [codykrieger/ace-rails-ap#5]
The ace editor works great in development, but when the asset pipeline isn't in debug mode, which is the case in production, I get 404 errors when trying to change editor "modes":

http://cl.ly/image/3w0H2W1e0635

I believe this has to do with the way RequireJS is used to load Ace modules, which depends on them being available as separate files.

**Comment by randoum** [comment]
If you guys can try my PR #16 and tell us if it fixes the problem in production, would be great
